# Generated by Django 4.1.5 on 2023-01-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charityorg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.IntegerField(verbose_name=20)),
            ],
        ),
    ]
