# Generated by Django 4.1.5 on 2023-01-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityorganization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='charityorg',
            table='charityorg',
        ),
    ]
